//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductBrowser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STØT;Initial Catalog=\"ABB Product Browser Database\";Integrated Securi" +
            "ty=True")]
        public string ABB_Product_Browser_DatabaseConnectionString {
            get {
                return ((string)(this["ABB_Product_Browser_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ASPIRER7;Initial Catalog=\"ABB Product Browser Database\";Integrated Se" +
            "curity=True")]
        public string ABB_Product_Browser_DatabaseConnectionString1 {
            get {
                return ((string)(this["ABB_Product_Browser_DatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEMOROOM-SUR40;Initial Catalog=\"ABB Product Browser Database\";Integra" +
            "ted Security=True")]
        public string ABB_Product_Browser_DatabaseConnectionString2 {
            get {
                return ((string)(this["ABB_Product_Browser_DatabaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=aspirer7;Initial Catalog=\"ABB Product Browser Database\";Integrated Se" +
            "curity=True")]
        public string ABB_Product_Browser_DatabaseConnectionString3 {
            get {
                return ((string)(this["ABB_Product_Browser_DatabaseConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=UX32V\\;Initial Catalog=\"ABB Product Browser Database\";Integrated Secu" +
            "rity=True")]
        public string ABB_Product_Browser_DatabaseConnectionString4 {
            get {
                return ((string)(this["ABB_Product_Browser_DatabaseConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHOWBOARD-SEC;Initial Catalog=\"ABB Product Browser Database\";Integrat" +
            "ed Security=True")]
        public string ABB_Product_Browser_DatabaseConnectionString5 {
            get {
                return ((string)(this["ABB_Product_Browser_DatabaseConnectionString5"]));
            }
        }
    }
}
